// USER
export const SET_USER = "SET_USER";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const FETCH_FOODTRUCK = "FETCH_FOODTRUCK";

//LOCATION
export const FETCH_HEATMAP = "FETCH_HEATMAP";
export const GET_LOCATION = "GET_LOCATION";

//CATEGORY
export const ADD_CATEGORY = "ADD_CATEGORY";
