// USER
export const SET_USER = "SET_USER";
export const FETCH_HEATMAP = "FETCH_HEATMAP";
export const FETCH_FOODTRUCK = "FETCH_FOODTRUCK";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const GET_LOCATION = "GET_LOCATION";
